function generateConfig() {
    const serverName = document.getElementById('serverName').value || 'Мой сервер';
    const modType = document.getElementById('modType').value;
    
    let config = `// AMXX Config Generated by AMXX Config Generator
// Server: ${serverName}
// Mod Type: ${modType}
// Generated: ${new Date().toLocaleString()}

echo "Конфиг загружен для сервера: ${serverName}"

// Основные настройки
amx_mode 1
amx_default_access "z"

`;

    // Добавляем настройки в зависимости от типа мода
    if (modType === 'zombie') {
        config += `// Zombie Plague настройки
zp_delay 15
zp_zombie_health 2500
zp_lighting "a"
`;
    } else if (modType === 'deathrun') {
        config += `// DeathRun настройки
dr_round_time 300
dr_trap_damage 25
`;
    }

    document.getElementById('configPreview').textContent = config;
}

function downloadConfig() {
    const config = document.getElementById('configPreview').textContent;
    const blob = new Blob([config], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'amxx.cfg';
    a.click();
    URL.revokeObjectURL(url);
}

// Генерируем начальный конфиг при загрузке
document.addEventListener('DOMContentLoaded', function() {
    generateConfig();
});