// Дополнительные функции для работы с конфигами
class ConfigBuilder {
    static generateUsersINI(admins) {
        let usersINI = `; users.ini - Generated by AMXX Config Generator
; Format: "auth" "password" "access" "flags"

`;
        // Здесь будет логика генерации users.ini
        return usersINI;
    }

    static generateMapsINI(maps) {
        let mapsINI = `; maps.ini - Generated by AMXX Config Generator
; Add your maps below

`;
        // Логика генерации maps.ini
        return mapsINI;
    }

    static validateCVAR(name, value) {
        // Простая валидация CVAR
        if (!name || name.trim() === '') {
            return 'Имя CVAR не может быть пустым';
        }
        
        if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) {
            return 'Некорректное имя CVAR';
        }
        
        return null;
    }
}